name: Production deployment on release

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      FORGE_EMAIL: ${{ vars.FORGE_EMAIL }}
      FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm install --global @forge/cli
          forge settings set usage-analytics true
          pip install pyyaml --upgrade
      - run: |
          cp .github/helpers/remove-display-conditions.py .
          python remove-display-conditions.py

          npm install
          forge deploy -e production
          forge install --upgrade -e production -s https://rayredberry.atlassian.net/ --product jira  --non-interactive